import type { Metadata, Viewport } from "next";

export const siteConfig = {
  name: "PT System",
  title: "PT System · Your AI trading mentor",
  description:
    "Aven is your AI trading mentor — trained on Paul's Wave Riding Method. Daily briefings, setup analysis, trade tracking. Try free for 14 days.",
  // Compact OG / Twitter copy — leaves room for the platform's name
  // ahead of the description in feed previews.
  socialDescription:
    "Aven sees your trades, knows Paul's method, coaches you 24/7. 14-day free trial.",
  url: "https://ptsystem.ai",
} as const;

export const baseMetadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: siteConfig.title,
    template: `%s — ${siteConfig.name}`,
  },
  description: siteConfig.description,
  applicationName: siteConfig.name,
  authors: [{ name: "Paul" }],
  creator: "Paul",
  publisher: "PT System",
  alternates: {
    canonical: "/",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteConfig.url,
    siteName: siteConfig.name,
    title: siteConfig.title,
    description: siteConfig.socialDescription,
    // Next.js auto-discovers `app/opengraph-image.tsx` and injects
    // og:image, og:image:width, og:image:height. No explicit
    // `images:` array needed here.
  },
  twitter: {
    card: "summary_large_image",
    title: siteConfig.title,
    description: siteConfig.socialDescription,
    // `app/twitter-image.tsx` is auto-discovered for twitter:image.
  },
  // Favicon resolution order:
  //   `app/icon.svg`         — modern browsers, scales crisp
  //   `app/apple-icon.png`   — iOS home-screen, auto-generated by
  //                            Next.js from the SVG when missing
  //   `/favicon.ico`         — legacy fallback
  // We ship only `app/icon.svg` for now; the .ico falls back to the
  // SVG render at small sizes.
};

export const baseViewport: Viewport = {
  themeColor: "#0a0a0a",
  colorScheme: "dark",
  width: "device-width",
  initialScale: 1,
};
